import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;

  return (
    <div className="flex w-full items-end gap-4">
      <img
        src={user.profileImageUrl}
        alt="Profile image"
        className="h-12 w-12 rounded-full"
      />
      <input
        type="text"
        placeholder="Type some emoji's !"
        className="h-full grow border-b border-slate-400 bg-transparent bg-zinc-800 pl-2 outline-none focus:rounded focus:border-2 focus:border-slate-400"
      />
    </div>
  );
};

export default function Home() {
  const user = useUser();
  const { data: posts, isLoading } = api.posts.getAll.useQuery();
  if (isLoading) return <div>Loading...</div>;
  if (!posts) return <div>Something went wrong !</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-slate-400">
            <div className="flex border-b-2 border-slate-400 p-4">
              {!user.isSignedIn && <SignInButton />}
              {!!user.isSignedIn && <CreatePostWizard />}
            </div>
            <div className="flex flex-col">
              {[...posts, ...posts]?.map((post) => (
                <div
                  className="border-b border-slate-400 p-8 text-center"
                  key={post.id}
                >
                  {post.content}
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
